[tool.poetry]
name = "hypothesis-testing-tool"
version = "0.1.0"
description = "A tool for doing hypothesis testing"
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
scipy = "^1.14.0"

[tool.poetry.dev-dependencies]
pytest = "^8.3.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
